"""Update the magic-byte signature table.

Reads a JSON file describing signatures and writes a Python module
into ``stegox.utils.magic``. Run by maintainers when adding new
formats.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def render_module(signatures: list[dict]) -> str:
    lines = ["# AUTO-GENERATED by tools/update_magic.py", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--in", dest="src", type=Path, required=True)
    args = parser.parse_args()
    data = json.loads(args.src.read_text(encoding="utf-8"))
    print(render_module(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
